# Generated by Django 2.2.5 on 2019-10-21 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private', models.BooleanField(default=False, help_text='This is a setting that you can trun on so pepole can not see you schedule if they are not your friend', verbose_name='Private profile?')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.png', upload_to='Profile_images')),
                ('friendRequest', models.IntegerField(default=0)),
                ('realname', models.CharField(default='', max_length=50)),
                ('realclass', models.CharField(default='', max_length=50)),
                ('age', models.IntegerField(default=0)),
                ('school', models.CharField(default='', max_length=50)),
                ('bio', models.TextField(blank=True, default='', help_text='Make your account more personal with a bio', max_length=500, null=True, verbose_name='Bio')),
                ('bf', models.ManyToManyField(blank=True, default=None, related_name='bf', to=settings.AUTH_USER_MODEL)),
                ('bff', models.ManyToManyField(blank=True, default=None, related_name='bff', to=settings.AUTH_USER_MODEL)),
                ('gf', models.ManyToManyField(blank=True, default=None, related_name='gf', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
