# Generated by Django 2.2.9 on 2020-02-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_exclude_schools_hours_links_schools_schools_hours'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bf',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gf',
        ),
        migrations.AddField(
            model_name='profile',
            name='acceptedlatest',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='accessamount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='allinfo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='hours',
            field=models.ManyToManyField(blank=True, default=None, to='schedule.Schools_hours'),
        ),
        migrations.AddField(
            model_name='profile',
            name='importsuccess',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_access',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='latestlink',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='realclass',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='realname',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='settings',
            name='private',
            field=models.BooleanField(default=True, help_text='This is a setting that you can trun on so pepole can not see you schedule if they are not your friend', verbose_name='Private profile?'),
        ),
    ]
