# Generated by Django 2.2.5 on 2019-10-21 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Timmar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField(default=django.utils.timezone.now)),
                ('enddate', models.DateField(default=django.utils.timezone.now)),
                ('starttime', models.TimeField(default=django.utils.timezone.now)),
                ('endtime', models.TimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=100)),
                ('subjecttext', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('frequense', models.IntegerField(choices=[(0, 'Only once'), (1, 'Everyday'), (2, 'Every other day'), (3, 'Every three days'), (4, 'Every four days'), (5, 'Every five days'), (6, 'Every six days'), (7, 'Every week')], default=0, help_text='How often do you want this event to happen?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExcludeTimmar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.TimeField(default=django.utils.timezone.now)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Timmar')),
            ],
        ),
    ]
