# Generated by Django 2.2.9 on 2020-02-02 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schools_hours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourhash', models.TextField(default='')),
                ('startdate', models.DateField(default=django.utils.timezone.now)),
                ('enddate', models.DateField(default=django.utils.timezone.now)),
                ('starttime', models.TimeField(default=django.utils.timezone.now)),
                ('endtime', models.TimeField(default=django.utils.timezone.now)),
                ('frequense', models.IntegerField(choices=[(0, 'Only once'), (1, 'Everyday'), (2, 'Every other day'), (3, 'Every three days'), (4, 'Every four days'), (5, 'Every five days'), (6, 'Every six days'), (7, 'Every week')], default=0, help_text='How often do you want this event to happen?')),
                ('title', models.CharField(max_length=100)),
                ('summary', models.TextField(default='')),
                ('location', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('resources', models.TextField(default='')),
                ('extra', models.TextField(default='')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Schools')),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exclude_schools_hours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.TimeField(default=django.utils.timezone.now)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('school_hour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Schools_hours')),
            ],
        ),
    ]
