# Generated by Django 2.2.9 on 2020-02-02 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friendship', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friendgroup',
        ),
    ]
